version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=${DB_USER:-appuser}
      - DB_NAME=${DB_NAME:-nerdybuddy}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET:-defaultsecret}
    volumes:
      - .:/nerdybuddy/src/app
      - /nerdybuddy/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgrespassword}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: